#!/bin/sh

# Dieses Script legt die wichtigsten Verzeichnisse an, die noch fehlen.

cd `dirname $0`/../..

if [ -f static/adm/LOAD_AT_STARTUP.org ]
then
   echo "Die Verzeichnisse wurden anscheinend schon angelegt."
   exit
fi
mkdir d
mkdir log
mkdir log/sys
mkdir p
mkdir save
# mkdir var
mkdir var/adm
mkdir var/adm/logfiles
mkdir var/adm/puffer
mkdir var/adm/news
mkdir var/intern
mkdir var/spool
mkdir var/statistik
mkdir var/statistik/buch
mkdir var/spool/wahlen
mkdir var/players
cd var/players
mkdir 0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z suicid wizzes
cd ../..
mkdir var/spool/mail
cd var/spool/mail
mkdir a b c d e f g h i j k l m n o p q r s t u v w x y z suicid
cd ../../..
mkdir var/spool/news
mkdir w
echo '*.*.*.*:0:-1:0:0:No msg' >> ACCESS.ALLOW
mv -i static/adm/examples/* static/adm/
